### PR TITLE
added lower-triangular matrix inverse

### PR DESCRIPTION
**Pull request by sunsided**
Added a matrix inversion algorithm for lower-triangular square matrices (e.g. the result of a cholesky decomposition).

### CODE REVIEW

**Comment by PetteriAimonen** [comment]
Hmm.. I tried adding a unit test (https://github.com/PetteriAimonen/libfixmatrix/commit/81c1e8b2a031838c5eebe3668b6ffb7bc3b4fe62) but it seems to be failing:

----Test mf16_invert_lt----
A =
   1.0000    0.0000    0.0000 
   2.0000    3.0000    0.0000 
   4.0000    5.0000    6.0000 
inv A =
   1.4568   -0.1913   -0.0185 
  -0.1913    0.1883   -0.0463 
  -0.0185   -0.0463    0.0278 
inv A \* A =
   1.0000   -0.6667   -0.1111 
   0.0000    0.3333   -0.2778 
   0.0000    0.0000    0.1667 
FAILED: fixmatrix_unittests.c:616 max_delta(&a, &identity) < 10

**Comment by PetteriAimonen** [comment]
Ah oops, it need to be symmetric.. what is a symmetric lower triangular matrix anyway?

**Comment by sunsided** [comment]
Argh, sorry! That should have read square! 

Petteri Aimonen notifications@github.com schrieb:

> Ah oops, it need to be symmetric.. what is a symmetric lower triangular
> matrix anyway?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/PetteriAimonen/libfixmatrix/pull/1#issuecomment-32521100

## 

Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by sunsided** [comment]
Well, yes - there's more to it. I massively borked up the description. 
This method is the inversion of a positive-definite matrix that has been 
decomposed to a lower triangular matrix.

if

A =

```
         1          0.5            0
       0.5            1            0
         0            0            1
```

and chol/lower

L =

```
         1            0            0
       0.5      0.86603        0
         0            0            1
```

then mf16_invert_lt(L, L) == inv(A)

it was a long day ...

------ Originalnachricht ------
Von: "Petteri Aimonen" notifications@github.com
An: "PetteriAimonen/libfixmatrix" libfixmatrix@noreply.github.com
Cc: "Markus Mayer" development@widemeadows.de
Gesendet: 16.01.2014 20:33:40
Betreff: Re: [libfixmatrix] added lower-triangular matrix inverse (#1)

**Comment by sunsided** [comment]
I have used the same algorithm [here](https://github.com/sunsided/kalman-clib/blob/master/Kalman/matrix_unittests.c) and have ported it to libfixmatrix for my Kalman filter library. There is a working unit test in [https://github.com/sunsided/libfixkalman/blob/develop/main.c](https://github.com/sunsided/libfixkalman/blob/develop/main.c#L6-L38). It's migrated from the other library and not fully done (read: unused variables and wrong comments), but you'll get the idea.

**Pull request merged**
